---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nxbuilder:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nxbuilder:latest
  - docker tag pdr.nephatrine.net/nephatrine/nxbuilder:latest nephatrine/nxbuilder:latest
  - HOME=/mnt/config/home docker push nephatrine/nxbuilder:latest
  - docker rmi pdr.nephatrine.net/nephatrine/nxbuilder:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-nxbuild-id
    webhook_token:
      from_secret: wh-nxbuild-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-nxbuilder@android
      - nephatrine/docker-nxbuilder@darwin
      - nephatrine/docker-nxbuilder@djgpp
      - nephatrine/docker-nxbuilder@freebsd
      - nephatrine/docker-nxbuilder@haiku
      - nephatrine/docker-nxbuilder@mingw
      - nephatrine/docker-nxbuilder@ubuntu

depends_on:
- default

---
kind: signature
hmac: 33f7720707872b72d1c406eae1ed54c4c777431dfdf52b637bb0edc11be54794

...
