---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nxbuilder:android .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nxbuilder:android
  - docker tag pdr.nephatrine.net/nephatrine/nxbuilder:android nephatrine/nxbuilder:android
  - HOME=/mnt/config/home docker push nephatrine/nxbuilder:android
  - docker rmi pdr.nephatrine.net/nephatrine/nxbuilder:android

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-nxbuild-id
    webhook_token:
      from_secret: wh-nxbuild-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: c4ad79cee0b1c2914618993e5035ce803749793d486db58bf396673dcb5524b6

...
