---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nxbuilder:centos .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nxbuilder:centos
  - docker tag pdr.nephatrine.net/nephatrine/nxbuilder:centos nephatrine/nxbuilder:centos
  - HOME=/mnt/config/home docker push nephatrine/nxbuilder:centos
  - docker rmi pdr.nephatrine.net/nephatrine/nxbuilder:centos

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-nxbuild-id
    webhook_token:
      from_secret: wh-nxbuild-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 8cd959e8cf356302a5652f141f1ec89891c36e74f3459eb8db05c66a7a6488be

...
