set(CMAKE_STATIC_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".lib")
set(CMAKE_EXECUTABLE_SUFFIX ".exe")

set(CMAKE_C_OUTPUT_EXTENSION ".o")
set(CMAKE_CXX_OUTPUT_EXTENSION ".o")

set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")

set(CMAKE_SYSTEM_INCLUDE_PATH /include)
set(CMAKE_SYSTEM_LIBRARY_PATH /lib)
set(CMAKE_SYSTEM_PROGRAM_PATH /bin)

set(CMAKE_POSITION_INDEPENDENT_CODE OFF)

include(Platform/WindowsPaths)

if("${CMAKE_C_COMPILER_TARGET}_${CMAKE_C_LIBRARY_ARCHITECTURE}" MATCHES "djgpp")
	set(CMAKE_SHARED_LIBRARY_PREFIX "")
	set(CMAKE_SHARED_LIBRARY_SUFFIX ".dxe")
	set(CMAKE_SHARED_MODULE_PREFIX "")
	set(CMAKE_SHARED_MODULE_SUFFIX ".dxe")
	set(CMAKE_IMPORT_LIBRARY_SUFFIX ".lib")

	set(CMAKE_C_CREATE_SHARED_LIBRARY "${CMAKE_DXEGEN} -U <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> -o <TARGET> -I <TARGET_IMPLIB> <OBJECTS> <LINK_LIBRARIES>")
	set(CMAKE_C_CREATE_SHARED_MODULE "${CMAKE_DXEGEN} -U <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")

	set(CMAKE_CXX_CREATE_SHARED_LIBRARY "${CMAKE_C_CREATE_SHARED_LIBRARY}")
	set(CMAKE_CXX_CREATE_SHARED_MODULE "${CMAKE_C_CREATE_SHARED_MODULE}")
else()
	set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
endif()
